name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: GitHub Action for Heroku
      uses: actions/heroku@1.0.0
    - name: Deploy app
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/hidden-crag-93128.git origin/master:master

