name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Checkout repository
    
    - name: Deploy app
      env:
        HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
      run: git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/hidden-crag-93128.git origin/master:master

